resolver: lts-18.23

packages:
- .

extra-deps:
# lts-18.23 uses aeson-1.5.6.0. We use this version with a patch applied to
# expose jsonEOF.
- git: https://github.com/stevehartdata/aeson.git
  commit: 9386637272569bcedae82325287dbabe21541bf6
- http-client-0.7.10
